name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Verify index.js existence
        run: ls editor/index.js

      - name: Rename index.js to index.cjs
        run: mv editor/index.js editor/index.cjs

      - name: Electron-builder compiler action
        uses: x6pnda/action-electron-compiler@v1.0.1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          package_manager: NPM
          skip_build: false
